### ISSUE TITLE
Weird line length spikes in Serbian, Croatian, Bosnian (data analysis task)

### ISSUE THREAD

**Issue by gordicaleksa** [gordicaleksa/Open-NLLB#22]
We get weird regularly spaced out histogram spikes for HBS languages, see below:

![image](https://github.com/gordicaleksa/Open-NLLB/assets/29271842/6f75e2b8-9ab9-4480-8350-164fee6984a5)

On the x-axis is the line length (in chars) and on the y-axis is the number of lines with that line length in our corpus.

Understand why this is happening and write a short report.

Instructions:
* Download the OPUS data using the `download_opus.py` script + some manual download see which datasets in the script (all those that are in the ignore list, see the OPUS website: https://opus.nlpl.eu/
* Use the `parse_macocu.py` to parse the MaCoCu data that has to be manually downloaded (for now, feel free to add functions to support the download through Python) from https://macocu.eu/ (only a couple of datasets so doesn't take too much time to do it manually).
* After that you can use the `analyse_data.py` script to replicate the graph above and then do your own analysis.

**Comment by smitz94** [comment]
Hi Aleksa, I would like to help in this !

**Comment by gordicaleksa** [comment]
Awesome!!

Let me know if you need some assistance: join the [Open-NLLB](https://discord.gg/59DZDWgR5a) channel if you haven't already.

**Comment by gordicaleksa** [comment]
Apparently the chart above was just a side effect of using a coarse number of bins for the histogram (500). If I instead use a fine-grained number the spikes dissapear.

![image](https://github.com/gordicaleksa/Open-NLLB/assets/29271842/201b5517-d34b-45d0-9ee1-10c9e316d92d)

**Comment by gordicaleksa** [comment]
Ok definitely just an artifact of how histogram was computed with number of bins smaller than the size of the x-axis.

Closing this one.
