### ISSUE TITLE
sub-batches creation

### ISSUE THREAD

**Issue by vienneraphael** [gordicaleksa/Open-NLLB#4]
Understand which optimizations are done in fairseq under the hood (sub-batches creation wrt. src/target len)
Explore fairseq codebase in this matter

# Question to answer
How are sub-batches generated wrt. src/target len in fairseq?

**Comment by gordicaleksa** [comment]
https://github.com/gordicaleksa/Open-NLLB/blob/nllb_replication/DATA_LOADING_EXPLAINED.md <- I think this document is a reply to this question.

If so - close the issue.
